set MATLAB=C:\Program Files\MATLAB\R2019b
"%MATLAB%\bin\%MATLAB_ARCH%\gmake" -f liner_control.mk  MAT_FILE=0 COMBINE_OUTPUT_UPDATE_FCNS=1 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING
